CREATE TABLE `Topic` (
	`Id`	INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Title`	TEXT NOT NULL
);

CREATE TABLE `Subject` (
	`Id`	INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Title`	TEXT NOT NULL,
	`TopicId`	INTEGER NOT NULL
);

CREATE TABLE `Note` (
	`Id`	INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Value`	TEXT NOT NULL,
	`SubjectId`	INTEGER NOT NULL,
	`Title`	TEXT
);
